name: crossplatform_asteroid_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  go_router: ^14.2.8
  json_annotation: ^4.9.0
  flame: ^1.19.0
  flame_forge2d: ^0.18.2
  get_it: ^7.7.0
  injectable: ^2.4.4
  dio: ^5.7.0
  flame_svg: ^1.11.0
  rive: ^0.7.30
  flame_rive: ^1.0.0
  flutter_svg: ^2.0.9
  throttling: ^2.0.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/